apiVersion: v1
kind: Service
metadata:
  name: {{ include "rakbank.fullname" . }}
  labels:
    {{- include "rakbank.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 8088
  selector:
    app: {{ include "rakbank.name" . }}
